project:
  type: website
  output-dir: docs
  render:
    - "**/*.qmd"
    - "!notes/00_template_lecture.qmd"
    - "!labs/00_template_lab_solution.qmd"
  resources:
    - psets/starter_code
    - .nojekyll          # stop GitHub Pages running the output through Jekyll

format:
  html:
    theme: [cosmo, custom_theme.scss]
    css: styles.css
    toc: false
    include-in-header: header.html
    page-layout: full
    math: mathjax

website:
  site-url: https://lucasrosenblatt.com/cs382
  favicon: favicon.ico
  navbar:
    css: styles.css
    title: "Fall 2026"
    search: false
    left:
      - text: "Piazza"
        href: "[PIAZZA_URL]"
      - text: "Slack"
        href: "[SLACK_CHANNEL_URL]"
      - text: "Syllabus"
        href: syllabus.html
      - text: "Labs"
        href: labs.html
      - text: "Project"
        href: project.html
